### ISSUE TITLE
Napalm cisco-ios fails to login

### ISSUE THREAD

**Issue by alias454** [napalm-automation/napalm-base#189]
Trying to setup napalm on a CentOS 7 VM to do some SaltStack testing and I not able to connect to the ios device from the cli. I can ssh to the device and login, but when using napalm, it doesn't work using cl_napalm_test.

I installed napalm using the following procedure
yum install gcc libffi-devel python-devel openssl-devel
yum install python2-pip
pip install --upgrade pip
pip install napalm

CentOS 7.3.1611 (Core)
Python 2.7.5

Please let me know if there is something I missed or what else I should try next

Below is the traceback 
```
[root@salt]# cl_napalm_test --vendor ios --user admin r1.alias454.local
Enter password:                                                                                                                  [51/9170]
NAPALM didn't catch this exception. Please, fill a bugfix on https://github.com/napalm-automation/napalm/issues
Don't forget to include this traceback.
Traceback (most recent call last):
  File "/bin/cl_napalm_test", line 9, in <module>
    load_entry_point('napalm-base==0.21.0', 'console_scripts', 'cl_napalm_test')()
  File "/usr/lib/python2.7/site-packages/napalm_base/clitools/cl_napalm_test.py", line 38, in main
    optional_args=optional_args) as device:
  File "/usr/lib/python2.7/site-packages/napalm_base/base.py", line 54, in __enter__
    self.__raise_clean_exception(exc_info[0], exc_info[1], exc_info[2])
  File "/usr/lib/python2.7/site-packages/napalm_base/base.py", line 82, in __raise_clean_exception
    raise exc_value
netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.
```

```
[root@salt-master router]# ssh admin@r1.alias454.local
Password:
MOTD Banner

R1>show ver
Cisco IOS Software, 2800 Software (C2800NM-ADVSECURITYK9-M), Version 15.1(4)M9, RELEASE SOFTWARE (fc3)
```

Regards,
Brandon

**Comment by bewing** [comment]
Is your MOTD banner actually "MOTD Banner", or is there something in there that may have confused prompt detection?

**Comment by alias454** [comment]
The banner is is actually MOTD banner
banner motd ^CMOTD Banner^C

**Comment by ktbyers** [comment]
@alias454 What happens when you execute this Netmiko script against the device:

```
#!/usr/bin/env python
from netmiko import ConnectHandler
from getpass import getpass

ip_addr = raw_input("Enter IP Address: ")

device = { 
    'device_type': 'cisco_ios',
    'ip': ip_addr,
    'username': 'admin',
    'password': getpass(),
} 

net_connect = ConnectHandler(**device)
output = net_connect.send_command("show ip int brief")
print(output)
```

**Comment by alias454** [comment]
That seems to work

```
[root@salt-master ~]# ./ios_test.py
Enter IP Address: 192.168.2.17
Password:
Interface                  IP-Address      OK? Method Status                Protocol
FastEthernet0/0            192.168.2.17    YES NVRAM  up                    up
FastEthernet0/1            192.168.100.1   YES NVRAM  up                    up
Loopback1                  1.1.1.1         YES NVRAM  up                    up
```

**Comment by ktbyers** [comment]
@alias454 What version of Netmiko are you using?

```
$ cl_napalm_test --vendor ios --user pyclass 10.10.10.70
Enter password: 
Successfully connected to the device
(napalm_py34)[gituser@ip-10-178-21-224 napalm-ios]$ pip list | grep netmiko
You are using pip version 7.0.3, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
netmiko (1.2.7)
(napalm_py34)[gituser@ip-10-178-21-224 napalm-ios]$ pip list | grep napalm-ios
You are using pip version 7.0.3, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
napalm-ios (0.5.1)
(napalm_py34)[gituser@ip-10-178-21-224 napalm-ios]$ pip list | grep napalm-base
You are using pip version 7.0.3, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
napalm-base (0.21.0)
```

**Comment by ktbyers** [comment]
Note, I made some improvements in the develop branch of Netmiko that might help with the issue.

https://github.com/ktbyers/netmiko/commit/a03638c1a2447204841bbd62af2d9c8d7b8ff60c

**Comment by mirceaulinic** [comment]
@alias454 do you still have the same issue with the latest releases? Please upgrade everything (`pip install -U napalm-ios` should be enough) and re-check.

**Comment by alias454** [comment]
@mirceaulinic Thanks for following up. I will check this as soon as I can and let you know.

**Comment by cgb** [comment]
Suggesting this be closed "no response from user"
