### ISSUE TITLE
The cryptography module in Debian Jessie does not work

### ISSUE THREAD

**Issue by monrad** [napalm-automation/napalm-base#57]
I tried using Napalm on a freshly installed Debian Jessie box and got the following error:
```
>>> from napalm_base import get_network_driver
>>> d = get_network_driver('DRIVER')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/napalm_base/__init__.py", line 73, in get_network_driver
    install_name=module_install_name
napalm_base.exceptions.ModuleImportError: Cannot import "napalm_driver". Is the library installed?
```
After trying `from napalm_junos import junos` that @dbarrosop told me to try I got:
```
>>> from napalm_junos import junos
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/napalm_junos/__init__.py", line 16, in <module>
    from junos import JunOSDriver
  File "/usr/local/lib/python2.7/dist-packages/napalm_junos/junos.py", line 19, in <module>
    from napalm_junos.utils import junos_views
  File "/usr/local/lib/python2.7/dist-packages/napalm_junos/utils/junos_views.py", line 4, in <module>
    from jnpr.junos.factory import loadyaml
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/__init__.py", line 1, in <module>
    from jnpr.junos.device import Device
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/device.py", line 16, in <module>
    from ncclient import manager as netconf_ssh
  File "/usr/local/lib/python2.7/dist-packages/ncclient/manager.py", line 22, in <module>
    from ncclient import operations
  File "/usr/local/lib/python2.7/dist-packages/ncclient/operations/__init__.py", line 16, in <module>
    from ncclient.operations.rpc import RPC, RPCReply, RPCError, RaiseMode
  File "/usr/local/lib/python2.7/dist-packages/ncclient/operations/rpc.py", line 20, in <module>
    from ncclient.transport import SessionListener
  File "/usr/local/lib/python2.7/dist-packages/ncclient/transport/__init__.py", line 18, in <module>
    from ncclient.transport.ssh import SSHSession
  File "/usr/local/lib/python2.7/dist-packages/ncclient/transport/ssh.py", line 26, in <module>
    import paramiko
  File "/usr/local/lib/python2.7/dist-packages/paramiko/__init__.py", line 30, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 53, in <module>
    from paramiko.dsskey import DSSKey
  File "/usr/local/lib/python2.7/dist-packages/paramiko/dsskey.py", line 27, in <module>
    from cryptography.hazmat.primitives.asymmetric.utils import (
ImportError: No module named utils
```
And after uninstalling the Debian provided module and installing from PIP it now works.

**Comment by dbarrosop** [comment]
NOTE: slightly edited your original comment

The issue here is that the dynamic loader is hiding the traceback and hinting that napalm_junos might not be installed. We should fix this so errors like these are propagated to the user.

**Comment by mirceaulinic** [comment]
@dbarrosop do you think we can kick off on this issue, or should we wait till https://github.com/napalm-automation/napalm-base/issues/109 is merged?

**Comment by dbarrosop** [comment]
Maybe it's better to wait, this is not super urgent and will make rebasing easier.
